<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;

use App\Models\CategoryMesin;
use App\Models\DetailMesin;
use App\Models\Mesin;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // \App\Models\User::factory(10)->create();

        // \App\Models\User::factory()->create([
        //     'name' => 'Test User',
        //     'email' => 'test@example.com',
        // ]);

        $category = [
            [
                'category' => 'Komponen',
            ],
            [
                'category' => 'Sistem',
            ],
        ];
        $mesin = [
            [
                'id_category' => '1',
                'kode_mesin' => 'komp001',
                'nama' => 'Blok Silinder',
                'fungsi' => '',
                'status' => 'Tidak Bergerak',
            ],
            [
                'id_category' => '1',
                'kode_mesin' => 'komp002',
                'nama' => 'Silinder',
                'fungsi' => '',
                'status' => 'Bergerak',
            ],
            [
                'id_category' => '1',
                'kode_mesin' => 'komp003',
                'nama' => 'Kepala Silinder',
                'fungsi' => '',
                'status' => 'Tidak Bergerak',
            ],
            [
                'id_category' => '1',
                'kode_mesin' => 'komp004',
                'nama' => 'Karter',
                'fungsi' => '',
                'status' => 'Tidak Bergerak',
            ],
            [
                'id_category' => '1',
                'kode_mesin' => 'komp005',
                'nama' => 'Front Engine Compartment',
                'fungsi' => '',
                'status' => 'null',
            ],
            [
                'id_category' => '1',
                'kode_mesin' => 'komp006',
                'nama' => 'Piston',
                'fungsi' => '',
                'status' => 'Bergerak',
            ],
            [
                'id_category' => '1',
                'kode_mesin' => 'komp007',
                'nama' => 'Batang Piston',
                'fungsi' => '',
                'status' => 'null',
            ],
            [
                'id_category' => '1',
                'kode_mesin' => 'komp008',
                'nama' => 'Poros Engkol',
                'fungsi' => '',
                'status' => 'Bergerak',
            ],
            [
                'id_category' => '1',
                'kode_mesin' => 'komp009',
                'nama' => 'Timing Gear',
                'fungsi' => '',
                'status' => 'Bergerak',
            ],
            [
                'id_category' => '1',
                'kode_mesin' => 'komp010',
                'nama' => 'Velve Mechanisme',
                'fungsi' => '',
                'status' => 'Bergerak',
            ],
            [
                'id_category' => '1',
                'kode_mesin' => 'komp011',
                'nama' => 'Fly Wheel',
                'fungsi' => '',
                'status' => 'Bergerak',
            ],
            [
                'id_category' => '1',
                'kode_mesin' => 'komp012',
                'nama' => 'Cam Shaft',
                'fungsi' => '',
                'status' => 'null',
            ],
            [
                'id_category' => '2',
                'kode_mesin' => 'sist001',
                'nama' => 'Starter',
                'fungsi' => '',
                'status' => 'null',
            ],
            [
                'id_category' => '2',
                'kode_mesin' => 'sist002',
                'nama' => 'Pengapian',
                'fungsi' => '',
                'status' => 'null',
            ],
            [
                'id_category' => '2',
                'kode_mesin' => 'sist003',
                'nama' => 'Pendinginan',
                'fungsi' => '',
                'status' => 'null',
            ],
            [
                'id_category' => '2',
                'kode_mesin' => 'sist004',
                'nama' => 'Bahan Bakar',
                'fungsi' => '',
                'status' => 'null',
            ],
            [
                'id_category' => '2',
                'kode_mesin' => 'sist005',
                'nama' => 'Pengisian',
                'fungsi' => '',
                'status' => 'null',
            ],
            [
                'id_category' => '2',
                'kode_mesin' => 'sist006',
                'nama' => 'Pelumas',
                'fungsi' => '',
                'status' => 'null',
            ],
            [
                'id_category' => '2',
                'kode_mesin' => 'sist007',
                'nama' => 'Pembuangan Sisa Gas',
                'fungsi' => '',
                'status' => 'null',
            ],
        ];
        $detail = [
            [
                'id_mesin' => '16',
                'nama' => 'Injeksi (untuk kendaraan bensin)',
                'type' => 'Sistem001',
                'latest_maintenance' => '2022-08-21',
                'next_maintenance' => '2026-08-21',
                'condition' => 'very good',
                'breakdown_possibility' => 99,
                'kode_mesin' => 'sistdet001',
            ],
            [
                'id_mesin' => '16',
                'nama' => 'Karburator',
                'type' => 'Sistem002',
                'latest_maintenance' => '2022-08-20',
                'next_maintenance' => '2026-08-20',
                'condition' => 'good',
                'breakdown_possibility' => 89,
                'kode_mesin' => 'sistdet002',
            ],
            [
                'id_mesin' => '16',
                'nama' => 'Injeksi (untuk kendaraan diesel)',
                'type' => 'Sistem003',
                'latest_maintenance' => '2022-08-19',
                'next_maintenance' => '2026-08-19',
                'condition' => 'bad',
                'breakdown_possibility' => 79,
                'kode_mesin' => 'sistdet003',
            ],
            [
                'id_mesin' => '16',
                'nama' => 'Gas Cair (LPG)',
                'type' => 'Sistem004',
                'latest_maintenance' => '2022-08-18',
                'next_maintenance' => '2026-08-18',
                'condition' => 'very good',
                'breakdown_possibility' => 98,
                'kode_mesin' => 'sistdet004',
            ],
            [
                'id_mesin' => '13',
                'nama' => 'Baterai',
                'type' => 'Sistem005',
                'latest_maintenance' => '2022-08-01',
                'next_maintenance' => '2024-08-01',
                'condition' => 'very good',
                'breakdown_possibility' => 97,
                'kode_mesin' => 'sistdet005',
            ],
            [
                'id_mesin' => '13',
                'nama' => 'Rellay',
                'type' => 'Sistem006',
                'latest_maintenance' => '2022-08-03',
                'next_maintenance' => '2024-08-03',
                'condition' => 'good',
                'breakdown_possibility' => 89,
                'kode_mesin' => 'sistdet006',
            ],
            [
                'id_mesin' => '13',
                'nama' => 'Motor Starter',
                'type' => 'Sistem007',
                'latest_maintenance' => '2022-08-05',
                'next_maintenance' => '2024-08-05',
                'condition' => 'bad',
                'breakdown_possibility' => 78,
                'kode_mesin' => 'sistdet007',
            ],
            [
                'id_mesin' => '13',
                'nama' => 'Kunci Kontak',
                'type' => 'Sistem008',
                'latest_maintenance' => '2022-08-07',
                'next_maintenance' => '2024-08-07',
                'condition' => 'very good',
                'breakdown_possibility' => 99,
                'kode_mesin' => 'sistdet008',
            ],
            [
                'id_mesin' => '3',
                'nama' => 'Kepala Silinder',
                'type' => 'XFJK',
                'latest_maintenance' => '2022-09-21',
                'next_maintenance' => '2026-09-21',
                'condition' => 'very good',
                'breakdown_possibility' => 99,
                'kode_mesin' => 'kompdet100',
            ],
            [
                'id_mesin' => '3',
                'nama' => 'Katup Hisap',
                'type' => 'XFJK1',
                'latest_maintenance' => '2022-09-20',
                'next_maintenance' => '2026-09-20',
                'condition' => 'good',
                'breakdown_possibility' => 89,
                'kode_mesin' => 'kompdet101',
            ],
            [
                'id_mesin' => '3',
                'nama' => 'Katup Buang',
                'type' => 'XFJK2',
                'latest_maintenance' => '2022-09-19',
                'next_maintenance' => '2026-09-19',
                'condition' => 'bad',
                'breakdown_possibility' => 79,
                'kode_mesin' => 'kompdet102',
            ],
            [
                'id_mesin' => '3',
                'nama' => 'Poros nok',
                'type' => 'XFJK3',
                'latest_maintenance' => '2022-09-18',
                'next_maintenance' => '2026-09-18',
                'condition' => 'very good',
                'breakdown_possibility' => 98,
                'kode_mesin' => 'kompdet103',
            ],
            [
                'id_mesin' => '3',
                'nama' => 'Rocker Arm',
                'type' => 'XFJK4',
                'latest_maintenance' => '2022-09-17',
                'next_maintenance' => '2026-09-17',
                'condition' => 'good',
                'breakdown_possibility' => 87,
                'kode_mesin' => 'kompdet104',
            ],
            [
                'id_mesin' => '3',
                'nama' => 'Cylinder Head Cover',
                'type' => 'XFJK5',
                'latest_maintenance' => '2022-09-16',
                'next_maintenance' => '2026-09-16',
                'condition' => 'bad',
                'breakdown_possibility' => 77,
                'kode_mesin' => 'kompdet105',
            ],
            [
                'id_mesin' => '3',
                'nama' => 'Busi',
                'type' => 'XFJK6',
                'latest_maintenance' => '2022-09-15',
                'next_maintenance' => '2026-09-15',
                'condition' => 'good',
                'breakdown_possibility' => 86,
                'kode_mesin' => 'kompdet106',
            ],
            [
                'id_mesin' => '3',
                'nama' => 'Intake Manifold',
                'type' => 'XFJK7',
                'latest_maintenance' => '2022-09-14',
                'next_maintenance' => '2026-09-14',
                'condition' => 'very good',
                'breakdown_possibility' => 96,
                'kode_mesin' => 'kompdet107',
            ],
            [
                'id_mesin' => '3',
                'nama' => 'Exhaust Manifold',
                'type' => 'XFJK8',
                'latest_maintenance' => '2022-09-13',
                'next_maintenance' => '2026-09-13',
                'condition' => 'good',
                'breakdown_possibility' => 85,
                'kode_mesin' => 'kompdet108',
            ],
            [
                'id_mesin' => '1',
                'nama' => 'Blok Silinder',
                'type' => 'XFJK9',
                'latest_maintenance' => '2022-09-23',
                'next_maintenance' => '2026-09-23',
                'condition' => 'good',
                'breakdown_possibility' => 86,
                'kode_mesin' => 'kompdet109',
            ],
            [
                'id_mesin' => '1',
                'nama' => 'Piston',
                'type' => 'XFJK10',
                'latest_maintenance' => '2022-09-01',
                'next_maintenance' => '2026-09-01',
                'condition' => 'very good',
                'breakdown_possibility' => 99,
                'kode_mesin' => 'kompdet110',
            ],
            [
                'id_mesin' => '1',
                'nama' => 'Ring Piston',
                'type' => 'XFJK11',
                'latest_maintenance' => '2022-09-22',
                'next_maintenance' => '2026-09-22',
                'condition' => 'good',
                'breakdown_possibility' => 89,
                'kode_mesin' => 'kompdet111',
            ],
            [
                'id_mesin' => '1',
                'nama' => 'Batang Penggerak',
                'type' => 'XFJK12',
                'latest_maintenance' => '2022-09-02',
                'next_maintenance' => '2026-09-02',
                'condition' => 'very good',
                'breakdown_possibility' => 97,
                'kode_mesin' => 'kompdet112',
            ],
            [
                'id_mesin' => '1',
                'nama' => 'Poros Engkol',
                'type' => 'XFJK13',
                'latest_maintenance' => '2022-09-04',
                'next_maintenance' => '2026-09-04',
                'condition' => 'very good',
                'breakdown_possibility' => 96,
                'kode_mesin' => 'kompdet113',
            ],
            [
                'id_mesin' => '1',
                'nama' => 'Carter/Oil Pan',
                'type' => 'XFJK14',
                'latest_maintenance' => '2022-09-05',
                'next_maintenance' => '2026-09-05',
                'condition' => 'very good',
                'breakdown_possibility' => 99,
                'kode_mesin' => 'kompdet114',
            ],
            [
                'id_mesin' => '1',
                'nama' => 'Drain Plug',
                'type' => 'XFJK15',
                'latest_maintenance' => '2022-09-06',
                'next_maintenance' => '2026-09-06',
                'condition' => 'good',
                'breakdown_possibility' => 86,
                'kode_mesin' => 'kompdet115',
            ],
            [
                'id_mesin' => '1',
                'nama' => 'Pulley Mesin',
                'type' => 'XFJK16',
                'latest_maintenance' => '2022-09-06',
                'next_maintenance' => '2026-09-06',
                'condition' => 'very good',
                'breakdown_possibility' => 98,
                'kode_mesin' => 'kompdet116',
            ],
            [
                'id_mesin' => '1',
                'nama' => 'Flywheel',
                'type' => 'XFJK17',
                'latest_maintenance' => '2022-09-16',
                'next_maintenance' => '2026-09-16',
                'condition' => 'very good',
                'breakdown_possibility' => 97,
                'kode_mesin' => 'kompdet117',
            ],
            [
                'id_mesin' => '5',
                'nama' => 'Timing Chain Assembly',
                'type' => 'XFJK18',
                'latest_maintenance' => '2022-09-15',
                'next_maintenance' => '2026-09-15',
                'condition' => 'very good',
                'breakdown_possibility' => 98,
                'kode_mesin' => 'kompdet118',
            ],
            [
                'id_mesin' => '5',
                'nama' => 'Timing Chain Cover',
                'type' => 'XFJK19',
                'latest_maintenance' => '2022-09-19',
                'next_maintenance' => '2026-09-19',
                'condition' => 'very good',
                'breakdown_possibility' => 99,
                'kode_mesin' => 'kompdet119',
            ],
            [
                'id_mesin' => '5',
                'nama' => 'Motor Starter',
                'type' => 'XFJK20',
                'latest_maintenance' => '2022-09-15',
                'next_maintenance' => '2026-09-15',
                'condition' => 'very good',
                'breakdown_possibility' => 97,
                'kode_mesin' => 'kompdet120',
            ],
            [
                'id_mesin' => '5',
                'nama' => 'Driver Belt',
                'type' => 'XFJK21',
                'latest_maintenance' => '2022-09-02',
                'next_maintenance' => '2026-09-02',
                'condition' => 'very good',
                'breakdown_possibility' => 100,
                'kode_mesin' => 'kompdet121',
            ],
            [
                'id_mesin' => '5',
                'nama' => 'Oil Cap',
                'type' => 'XFJK22',
                'latest_maintenance' => '2022-09-04',
                'next_maintenance' => '2026-09-04',
                'condition' => 'good',
                'breakdown_possibility' => 90,
                'kode_mesin' => 'kompdet122',
            ],
            [
                'id_mesin' => '15',
                'nama' => 'Radiator',
                'type' => 'XFJK23',
                'latest_maintenance' => '2022-09-05',
                'next_maintenance' => '2026-09-05',
                'condition' => 'very good',
                'breakdown_possibility' => 100,
                'kode_mesin' => 'kompdet123',
            ],
            [
                'id_mesin' => '15',
                'nama' => 'tutup Radiator',
                'type' => 'XFJK24',
                'latest_maintenance' => '2022-09-07',
                'next_maintenance' => '2026-09-07',
                'condition' => 'very good',
                'breakdown_possibility' => 100,
                'kode_mesin' => 'kompdet124',
            ],
            [
                'id_mesin' => '15',
                'nama' => 'Thermostat',
                'type' => 'XFJK25',
                'latest_maintenance' => '2022-09-07',
                'next_maintenance' => '2026-09-07',
                'condition' => 'very good',
                'breakdown_possibility' => 96,
                'kode_mesin' => 'kompdet125',
            ],
            [
                'id_mesin' => '15',
                'nama' => 'Cooling Fan',
                'type' => 'XFJK26',
                'latest_maintenance' => '2022-09-08',
                'next_maintenance' => '2026-09-08',
                'condition' => 'very good',
                'breakdown_possibility' => 100,
                'kode_mesin' => 'kompdet126',
            ],
            [
                'id_mesin' => '15',
                'nama' => 'Reservoir Tank (Tangki Cadangan)',
                'type' => 'XFJK27',
                'latest_maintenance' => '2022-09-09',
                'next_maintenance' => '2026-09-09',
                'condition' => 'very good',
                'breakdown_possibility' => 100,
                'kode_mesin' => 'kompdet127',
            ],
            [
                'id_mesin' => '15',
                'nama' => 'Upper Hose & Lower Hose',
                'type' => 'XFJK28',
                'latest_maintenance' => '2022-09-08',
                'next_maintenance' => '2026-09-08',
                'condition' => 'very good',
                'breakdown_possibility' => 99,
                'kode_mesin' => 'kompdet128',
            ],
            [
                'id_mesin' => '15',
                'nama' => 'Water Temperatur Sensor',
                'type' => 'XFJK29',
                'latest_maintenance' => '2022-09-07',
                'next_maintenance' => '2026-09-07',
                'condition' => 'very good',
                'breakdown_possibility' => 98,
                'kode_mesin' => 'kompdet129',
            ],
            [
                'id_mesin' => '15',
                'nama' => 'Water Jacket',
                'type' => 'XFJK30',
                'latest_maintenance' => '2022-09-11',
                'next_maintenance' => '2026-09-11',
                'condition' => 'very good',
                'breakdown_possibility' => 97,
                'kode_mesin' => 'kompdet130',
            ],
            [
                'id_mesin' => '15',
                'nama' => 'V-Belt (Sabuk Penggerak)',
                'type' => 'XFJK31',
                'latest_maintenance' => '2022-09-12',
                'next_maintenance' => '2026-09-12',
                'condition' => 'very good',
                'breakdown_possibility' => 97,
                'kode_mesin' => 'kompdet131',
            ],
            [
                'id_mesin' => '17',
                'nama' => 'Alternator',
                'type' => 'XFJK31',
                'latest_maintenance' => '2022-09-12',
                'next_maintenance' => '2026-09-12',
                'condition' => 'very good',
                'breakdown_possibility' => 98,
                'kode_mesin' => 'kompdet131',
            ],
            [
                'id_mesin' => '17',
                'nama' => 'Regulator',
                'type' => 'XFJK32',
                'latest_maintenance' => '2022-09-13',
                'next_maintenance' => '2026-09-13',
                'condition' => 'very good',
                'breakdown_possibility' => 98,
                'kode_mesin' => 'kompdet132',
            ],
            [
                'id_mesin' => '17',
                'nama' => 'Baterai',
                'type' => 'XFJK32',
                'latest_maintenance' => '2022-08-12',
                'next_maintenance' => '2026-08-12',
                'condition' => 'good',
                'breakdown_possibility' => 89,
                'kode_mesin' => 'kompdet132',
            ],
            [
                'id_mesin' => '18',
                'nama' => 'Pompa Oli (Pump Oil)',
                'type' => 'XFJK33',
                'latest_maintenance' => '2022-08-01',
                'next_maintenance' => '2026-08-01',
                'condition' => 'good',
                'breakdown_possibility' => 89,
                'kode_mesin' => 'kompdet133',
            ],
            [
                'id_mesin' => '18',
                'nama' => 'Saringan Oli',
                'type' => 'XFJK34',
                'latest_maintenance' => '2022-08-02',
                'next_maintenance' => '2026-08-02',
                'condition' => 'very good',
                'breakdown_possibility' => 99,
                'kode_mesin' => 'kompdet134',
            ],
            [
                'id_mesin' => '18',
                'nama' => 'Saringan Kasa Oli',
                'type' => 'XFJK35',
                'latest_maintenance' => '2022-08-03',
                'next_maintenance' => '2026-08-03',
                'condition' => 'very good',
                'breakdown_possibility' => 98,
                'kode_mesin' => 'kompdet135',
            ],
            [
                'id_mesin' => '16',
                'nama' => 'Tangki Bahan Bakar (Fuel Tank)',
                'type' => 'XFJK36',
                'latest_maintenance' => '2022-08-04',
                'next_maintenance' => '2026-08-04',
                'condition' => 'very good',
                'breakdown_possibility' => 98,
                'kode_mesin' => 'kompdet136',
            ],
            [
                'id_mesin' => '16',
                'nama' => 'Saringan Bahan Bakar (Fuel Filter)',
                'type' => 'XFJK37',
                'latest_maintenance' => '2022-08-05',
                'next_maintenance' => '2026-08-05',
                'condition' => 'very good',
                'breakdown_possibility' => 98,
                'kode_mesin' => 'kompdet137',
            ],
            [
                'id_mesin' => '16',
                'nama' => 'Saluran Bahan Bakar',
                'type' => 'XFJK37',
                'latest_maintenance' => '2022-08-06',
                'next_maintenance' => '2026-08-06',
                'condition' => 'very good',
                'breakdown_possibility' => 97,
                'kode_mesin' => 'kompdet137',
            ],
            [
                'id_mesin' => '16',
                'nama' => 'Pompa Bahan Bakar',
                'type' => 'XFJK38',
                'latest_maintenance' => '2022-08-06',
                'next_maintenance' => '2026-08-06',
                'condition' => 'very good',
                'breakdown_possibility' => 96,
                'kode_mesin' => 'kompdet138',
            ],
            [
                'id_mesin' => '16',
                'nama' => 'Karburator',
                'type' => 'XFJK39',
                'latest_maintenance' => '2022-08-07',
                'next_maintenance' => '2026-08-07',
                'condition' => 'very good',
                'breakdown_possibility' => 97,
                'kode_mesin' => 'kompdet139',
            ],
        ];

        CategoryMesin::insert($category);
        Mesin::insert($mesin);
        DetailMesin::insert($detail);
    }
}
